# Generated by Django 2.0.5 on 2018-08-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsedetails',
            name='experiance',
            field=models.FloatField(),
        ),
    ]
